# AfnwCore2 Config File
# AfnwCore2に関するいろんな設定を変更できるファイルです。パーミッションの設定はここでは行えません。
# 編集した後はサーバーを再起動するか、プラグインを再リロードするか、コマンド "/reload#afnw" を実行してください。
# デフォルト値は万が一指定されていないときにAfnwCore2が代入する値です。(World名のConfigではデフォルト値が入ってもワールドが見つからない場合はRuntimeException(例外)としてクラッシュします。)

vote: # 投票周りの設定
  item-size: 1
  # /afnwで交換できるアイテムの数を指定してください。int(数)ではない場合はエラーが発生します。デフォルト: 1
  scaffold-size: 8
  # /afnwで交換時に一緒に配布される足場の数を指定してください。int(数)ではない場合はエラーが発生します。デフォルト: 8
  send-ticket-size: 1
  # 投票時に受け取れるチケットの数を指定してください。int(数)ではない場合はエラーが発生します。デフォルト: 1

tp:
  standby: 10
  # TPコマンド(not /tp)を使用した際の待機時間を病で指定します。int(数)ではない場合はエラーが発生します。デフォルト: 10
  lobby_world_name: "lobby"
  # ロビーワールドの名前を指定します。
