# AfnwCore2 Config File
# AfnwCore2に関するいろんな設定を変更できるファイルです。パーミッションの設定はここでは行えません。
# 編集した後はサーバーを再起動するか、プラグインを再リロードするか、コマンド "/reload#afnw" を実行してください。

vote: # 投票周りの設定
  item-size: 1
  # /afnwで交換できるアイテムの数を指定してください。int(数)ではない場合はエラーが発生します。デフォルト: 1
  scaffold-size: 8
  # /afnwで交換時に一緒に配布される足場の数を指定してください。int(数)ではない場合はエラーが発生します。デフォルト: 8
